# * kubectl aliases

alias k='kubectl'
alias kd='kubectl describe'
alias kl='kubectl logs'
alias kex='kubectl exec -it'
alias kaf='kubectl apply -f'
alias kdf='kubectl delete -f'
alias kgs='kubectl get svc'
alias kgn='kubectl get node'
alias kac='kubectl auth can-i'
alias kaw='kubectl auth whoami'
alias kgp='kubectl get pod'
alias kdm='kubectl get daemonset'
alias kgd='kubectl get deployment'
alias kgpv='kubectl get pv'
alias kgsa='kubectl get serviceaccount'
alias kgcm='kubectl get configmap'
alias kgcj='kubectl get cronjob'
alias kgns='kubectl get namespace'
alias kgpvc='kubectl get pvc'
alias kga='kubectl get all -A'
alias kdel='kubectl delete'
alias kgsec='kubectl get secret'
alias kgcrd='kubectl get crd'
alias kgnet='kubectl get networkpolicies'
